### ISSUE TITLE
Regex-based dropping is not sound

### ISSUE THREAD

**Issue by DM-Berger** [stfxecutables/df-analyze#21]
The hacky column selection in `hypertune.py` of course fails on data with trash feature names. Either we need to properly handle column name selection or rename junk feature names to only include e.g. ASCII and non-regex special characters. 

**`df-analyze` Output**

```
Traceback (most recent call last):
  File "/scratch/[redacted]/df-analyze/src/hypertune.py", line 368, in _get_splits
    X_train = prep_train.X.filter(regex="|".join(cols))
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5723, in filter
    matcher = re.compile(regex)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/root/.pyenv/versions/3.10.12/lib/python3.10/sre_parse.py", line 672, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 3438

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/[redacted]/df-analyze/test/test_main.py", line 167, in <module>
    do_main((dsname, ds))
  File "/scratch/[redacted]/df-analyze/test/test_main.py", line 126, in do_main
    eval_results = evaluate_tuned(
  File "/scratch/[redacted]/df-analyze/src/hypertune.py", line 415, in evaluate_tuned
    X_train, X_test = _get_splits(prep_train, prep_test, selection, selected_cols)
  File "/scratch/[redacted]/df-analyze/src/hypertune.py", line 379, in _get_splits
    X_train = prep_train.X.drop(list(to_drop))
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['speaks_english french spanish', 'sign_leo but it doesn&rsquo;t matter', 'speaks_english (fluently) spanish', 'speaks_english italian (okay)', 'speaks_english (fluently) vietnamese (okay)', 'religion_agnosticism', 'orientation_g
ay', 'pets_has dogs and dislikes cats', 'speaks_english (fluently) japanese (okay)'
[...]
```

**Data To Reproduce**
This is the `okcupid-stem` test dataset. Error occurred on Compute Canada Niagara in an array job

**Comment by DM-Berger** [comment]
I just tested a run of this locally on MacOS and unfortunately was not able to replicate the error. It is not clear to me why / how this could be an intermittent bug at the moment... will investigate further.
