### ISSUE TITLE
`ValueError: Index contains duplicate entries` when creating wide tables

### ISSUE THREAD

**Issue by DM-Berger** [stfxecutables/df-analyze#23]
**Describe the bug**
Something seems to rarely go wrong when creating the wide_table:

**Paste `df-analyze` Output**

```
Traceback (most recent call last):
  File "/scratch/[redacted]/df-analyze/test/test_main.py", line 167, in <module>
    do_main((dsname, ds))
  File "/scratch/[redacted]/df-analyze/test/test_main.py", line 135, in do_main
    print(eval_results.to_markdown())
  File "/scratch/[redacted]/df-analyze/src/hypertune.py", line 285, in to_markdown
    df_train = self.wide_table("trainset")
  File "/scratch/[redacted]/df-analyze/src/hypertune.py", line 272, in wide_table
    self.df.drop(columns=cols)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 9025, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/reshape/pivot.py", line 553, in pivot
    result = indexed.unstack(columns_listlike)  # type: ignore[arg-type]
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 4459, in unstack
    return unstack(self, level, fill_value, sort)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 517, in unstack
    unstacker = _Unstacker(
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 154, in __init__
    self._make_selectors()
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/reshape/reshape.py", line 210, in _make_selectors
    raise ValueError("Index contains duplicate entries, cannot reshape")
ValueError: Index contains duplicate entries, cannot reshape

```

**Data To Reproduce**
This happened on the `ozone_level` dataset on the Niagara cluster.

**Comment by DM-Berger** [comment]
I just tested a run of this locally on MacOS and unfortunately was not able to replicate the error. I also tested locally using the exact same `options.json` that produced the error on the cluster (albeit reducing the number of tuning rounds) and still was not able to reproduce... 

 It is not clear to me why / how this could be an intermittent bug at the moment...

**Comment by DM-Berger** [comment]
As the problem currently exists only when calling the `EvaluationResults.wide_table` function, for now, I have just wrapped this in a try/catch (https://github.com/stfxecutables/df-analyze/commit/b57813f568514153e7a6b050d0d361a00ed3cc39). The key output table (`EvaluationResults.df`) is still produced without issues, it seems, so at least that will now be saved and can be used to debug whatever exactly is going on here (and to generate the final report after the fact).

**Comment by DM-Berger** [comment]
Fixed by https://github.com/stfxecutables/df-analyze/commit/9db6c6fcabde707ab0c032a8acf86bdf1796794f.

**Comment by DM-Berger** [comment]
Turns out this was caused by the creation (somehow) of NaN rows in the main long / tall performance DataFrame. Dropping them resolves the issue. See https://github.com/stfxecutables/df-analyze/commit/095a8ddd8e2420a414c684f55b733c27a0337c44.
