### ISSUE TITLE
Undersampled levels error

### ISSUE THREAD

**Issue by theahmadzai** [stfxecutables/df-analyze#28]
**Describe the bug**
I'm trying to run the dataset but it throws an error `ValueError: Target 'price' has undersampled levels`

**Paste `df-analyze` Output**

```sh
/Users/theahmadzai/github/df-analyze/src/cli/cli.py:372: UserWarning: Without pruning, Optuna generally only shows clear superiority
to random search at roughly 50-100 trials. See e.g.
    Akiba et al. (2019)
    Optuna: A Next-generation Hyperparameter Optimization Framework 
    https://arxiv.org/pdf/1907.10902.pdf
For deep learners, e.g. if using `mlp` as either a classifer
or regressor, experience suggests more like 100-200 trials (with
pruning) are needed when exploring new architectures. For the
current MLP architecture, probably 100 trials is sufficient.

  warn(
No test datasets found. If you are not a developer of df-analyze, you may ignore this message.
<class 'list'> ['knn', 'lgbm', 'rf', 'lr', 'sgd', 'dummy']
<class 'list'> ['knn', 'lgbm', 'rf', 'elastic', 'sgd', 'dummy']
<class 'list'> [<FeatureSelection.Filter: 'filter'>, <FeatureSelection.Embedded: 'embed'>, <FeatureSelection.Wrapper: 'wrap'>]
<class 'list'> [<EmbedSelectionModel.LGBM: 'lgbm'>, <EmbedSelectionModel.Linear: 'linear'>]
To silence these warnings, use `--verbosity=0`.
Will run analyses with options:
{ 'categoricals': [],
  'classifiers': ( <DfAnalyzeClassifier.Dummy: 'dummy'>,
                   <DfAnalyzeClassifier.KNN: 'knn'>,
                   <DfAnalyzeClassifier.LGBM: 'lgbm'>,
                   <DfAnalyzeClassifier.LR: 'lr'>,
                   <DfAnalyzeClassifier.RF: 'rf'>,
                   <DfAnalyzeClassifier.SGD: 'sgd'>),
  'comparables': { 'model': (...),
                   'norm': <Normalization.Robust: 'robust'>,
                   'selection': (...)},
  'datapath': PosixPath('/Users/theahmadzai/github/df-analyze/out.csv'),
  'drops': [],
  'embed_select': ( <EmbedSelectionModel.LGBM: 'lgbm'>,
                    <EmbedSelectionModel.Linear: 'linear'>),
  'feat_select': ( <FeatureSelection.Embedded: 'embed'>,
                   <FeatureSelection.Filter: 'filter'>,
                   <FeatureSelection.Wrapper: 'wrap'>),
  'filter_assoc_cat_cls': <CatClsStats.MutualInfo: 'mut_info'>,
  'filter_assoc_cat_reg': <CatRegStats.MutualInfo: 'mut_info'>,
  'filter_assoc_cont_cls': <ContClsStats.MutualInfo: 'mut_info'>,
  'filter_assoc_cont_reg': <ContRegStats.MutualInfo: 'mut_info'>,
  'filter_pred_cls_score': <ClsScore.Accuracy: 'acc'>,
  'filter_pred_reg_score': <RegScore.MAE: 'mae'>,
  'htune_cls_metric': ClassifierScorer(),
  'htune_reg_metric': RegressorScorer(),
  'htune_trials': 50,
  'is_classification': True,
  'is_spreadsheet': False,
  'n_feat_filter': 0.5,
  'n_feat_wrapper': 20,
  'n_filter_cat': 0.5,
  'n_filter_cont': 0.5,
  'nan_handling': <NanHandling.Median: 'median'>,
  'no_warn_explosion': False,
  'norm': <Normalization.Robust: 'robust'>,
  'ordinals': [],
  'outdir': PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out'),
  'program_dirs': ProgramDirs(root=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda'),
                              terminal=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/terminal_outputs.txt'),
                              options=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/options.json'),
                              joblib_cache=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/__JOBLIB_CACHE__'),
                              renames=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/feature_renamings.md'),
                              inspection=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/inspection'),
                              prepared=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/prepared'),
                              features=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/features'),
                              associations=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/features/associations'),
                              predictions=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/features/predictions'),
                              selection=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/selection'),
                              filter=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/selection/filter'),
                              embed=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/selection/embed'),
                              wrapper=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/selection/wrapper'),
                              tuning=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/tuning'),
                              results=PosixPath('/Users/theahmadzai/github/df-analyze/df_analyze_results/out/8850a7c33b683162c1b76019c39e3bda/results'),
                              needs_clean=False),
  'redundant_corr_threshold': 0.8,
  'redundant_selection': True,
  'redundant_threshold': 0.005,
  'regressors': ( <DfAnalyzeRegressor.Dummy: 'dummy'>,
                  <DfAnalyzeRegressor.ElasticNet: 'elastic'>,
                  <DfAnalyzeRegressor.KNN: 'knn'>,
                  <DfAnalyzeRegressor.LGBM: 'lgbm'>,
                  <DfAnalyzeRegressor.RF: 'rf'>,
                  <DfAnalyzeRegressor.SGD: 'sgd'>),
  'separator': ',',
  'target': 'price',
  'test_val_size': 0.4,
  'verbosity': <Verbosity.INFO: 1>,
  'wrapper_model': <WrapperSelectionModel.Linear: 'linear'>,
  'wrapper_select': <WrapperSelection.StepUp: 'step-up'>}

=================================================================================
InspectionInfo
...............
Found features likely containing identifiers (i.e. unique string or integer values that are assigned arbitrarily), or which have more levels (unique values) than one half of the number of (non-NaN) samples in the data. This is most likely an identifier or junk feature which has no predictive value, and thus should be removed from the data. Even if the feature is not an identifer, with such a large number of levels, then a test set (either in k-fold, or holdout) will, on average, mostly contain values that were never seen during training. Thus, these features are essentially undersampled, and too sparse to be useful given the amount of data. Encoding this many values also massively increases compute costs for little gain. We thus REMOVE these features. However, but you should inspect these features yourself and ensure these features are not better described as either ordinal or continuous. If so, specify them using the `--ordinals` `--continous` options to df-analyze.

Features inferred to be identifiers:

name        More unique values than one half of number of non-NaN samples
id          All values including possible NaNs are unique
Unnamed_0   All values including possible NaNs are unique
=================================================================================

=================================================================================
InspectionInfo
...............
Found features with only two unique values. These will be treated as binary categorical.
=================================================================================

=================================================================================
InspectionInfo
...............
Found features that are mostly or entirely continuous values. This means either that these columns convert to a floating point representation without any loss of information, or that most (e.g. over 80%) of the values do. df-analyze will automatically treat these columns as continuous to prevent wasted compute resources that would be incurred with encoding them as categorical, however, this might be an error.

Columns inferred to be continuous:

latitude    All values are not integers and convert to float
name        More than 20% of values parse as floats, but couldn't parse values: ['!! Large 3 Bedroom Apartment in NYC!!', '!!! Designer room in NYC!!! 12 min to Time Square', '!!Beautiful Large 3 Bedroom Apartment in NYC!!', '!!Charming 3bedroom apartment on upper west side!!', '!!Studio next to Empire State Bldg.' ...]
longitude   All values are not integers and convert to float
=================================================================================

=================================================================================
InspectionInfo
...............
Found features that could contain ordinal values (i.e. non-categorical integer values). Check if these features are ordinal or categorical, and then explicitly pass them to either the `--categoricals` or `--ordinals` options when configuring df-analyze.

Columns inferred to be ordinal:

neighbourhood_labelencoded   Increasing integers in [0, 222]
number_of_reviews            80% or more of unique integer values differ only by 1
availability_365             Increasing integers in [0, 365]
=================================================================================

=================================================================================
InspectionInfo
...............
Found features that look categorical. These will be one-hot encoded to allow use in subsequent analyses. To silence this warning, specify them as categoricals or ordinals manually either via the CLI or in the spreadsheet file header, using the `--categoricals` and/or `--ordinals` option.

Features that may be categorical:

neighbourhood_labelencoded   Looks both categorical and ordinal
number_of_reviews            Looks both categorical and ordinal
availability_365             Looks both categorical and ordinal
minimum_nights               Integer data but not ordinal-like
=================================================================================

=================================================================================
Found Messy Data
.................
df-analyze could not determine the types of some features. These have been coerced to our best guess for the appropriate type. See reports for details. This warning cannot be silenced unless you properly identify these features with the `--categoricals` and `--ordinals` options to df-analyze.

Ambiguous columns: {'neighbourhood_labelencoded': [Inference(MaybeOrd: Increasing integers in [0, 222]), Inference(MaybeCat: Looks both categorical and ordinal)], 'number_of_reviews': [Inference(MaybeOrd: 80% or more of unique integer values differ only by 1), Inference(MaybeCat: Looks both categorical and ordinal)], 'availability_365': [Inference(MaybeOrd: Increasing integers in [0, 365]), Inference(MaybeCat: Looks both categorical and ordinal)], 'minimum_nights': [Inference(MaybeCat: Integer data but not ordinal-like)]}.
=================================================================================

=================================================================================
InspectionInfo
...............
Found features that, when interpreted as categorical, have more than 50 unique levels / classes. Unless you have a large number of samples, or if these features have a highly imbalanced / skewed distribution, then they will cause sparseness after one-hot encoding. This is generally not beneficial to most algorithms. You should inspect these features and think if it makes sense if they would be predictively useful for the given target. If they are unlikely to be useful, consider removing them from the data. This will also likely considerably improve `df-analyze` predictive performance and reduce compute times. However, we do NOT remove these features automatically.

Features with over 50 levels when interpreted as categorical: minimum_nights   128 levels
=================================================================================

=================================================================================
Cleaning Data Features
.......................
Dropping features that appear to be identifiers. Additional information should be available above.

Dropped features:
Unnamed_0   Inference(CertainId: All values including possible NaNs are unique)
id          Inference(CertainId: All values including possible NaNs are unique)
name        Inference(MaybeId: More unique values than one half of number of non-NaN samples)
=================================================================================

=================================================================================
Found Messy Data
.................
Found and 'deflated' a number of categorical variables with levels that are unlikely to be reliable or useful in prediction. For each level of categorical variable to be predictively useful, there must be enough samples to be statistically meaningful (or to allow some reasonable generalization) in each fold used for fitting or analyses. Roughly, this means each fold needs to see at least 10-20 samples of each level (depending on how strongly / cleanly the level relates to other features - ultimately this is just a heuristic). Assuming k-fold is used for validation, then this means about k*10 samples per categorical level would a reasonable default minimum requirement one might use for culling categorical levels. Under the typical assumption of k=5, this means we require useful / reliable categorical levels to have 50 samples each.

Deflated categorical variables (before --> after):
minimum_nights   128 --> 30
=================================================================================

=================================================================================
Found Messy Data
.................
Found and 'deflated' a number of categorical variables with levels that are unlikely to be reliable or useful in prediction. For each level of categorical variable to be predictively useful, there must be enough samples to be statistically meaningful (or to allow some reasonable generalization) in each fold used for fitting or analyses. Roughly, this means each fold needs to see at least 10-20 samples of each level (depending on how strongly / cleanly the level relates to other features - ultimately this is just a heuristic). Assuming k-fold is used for validation, then this means about k*10 samples per categorical level would a reasonable default minimum requirement one might use for culling categorical levels. Under the typical assumption of k=5, this means we require useful / reliable categorical levels to have 50 samples each.

Deflated categorical variables (before --> after):
minimum_nights   128 --> 30
=================================================================================
Traceback (most recent call last):
  File "/Users/theahmadzai/github/df-analyze/df-analyze.py", line 162, in <module>
    main()
  File "/Users/theahmadzai/github/df-analyze/df-analyze.py", line 111, in main
    prepared = prepare_data(df, target, inspection, is_cls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theahmadzai/github/df-analyze/src/preprocessing/prepare.py", line 481, in prepare_data
    return PreparedData(
           ^^^^^^^^^^^^^
  File "/Users/theahmadzai/github/df-analyze/src/preprocessing/prepare.py", line 229, in __init__
    X, X_cont, X_cat, y = self.validate(X, X_cont, X_cat, y)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/theahmadzai/github/df-analyze/src/preprocessing/prepare.py", line 337, in validate
    raise ValueError(f"Target '{y.name}' has undersampled levels")
ValueError: Target 'price' has undersampled levels
```

**Data To Reproduce**
```sh
#!/bin/bash

python df-analyze.py \
  --df out.csv \
  --target price \
  --mode classify \
  --classifiers knn lgbm rf lr sgd dummy \
  --regressors knn lgbm rf elastic sgd dummy \
  --feat-select filter embed wrap \
  --redundant-wrapper-selection \
  --embed-select lgbm linear \
  --wrapper-select step-up \
  --wrapper-model linear \
  --norm robust \
  --nan median \
  --filter-method assoc pred \
  --filter-assoc-cont-classify mut_info \
  --filter-assoc-cat-classify mut_info \
  --filter-assoc-cont-regress mut_info \
  --filter-assoc-cat-regress mut_info \
  --filter-pred-regress mae \
  --filter-pred-classify acc \
  --htune-trials 50 \
  --htune-cls-metric acc \
  --htune-reg-metric mae \
  --test-val-size 0.4 \
  --outdir ./df_analyze_results
  ```

**Comment by DM-Berger** [comment]
Hey @theahmadzai .

This is not a bug, but rather a very strong indication that your dataset is far too small to be doing machine learning on. In particular, if you run afoul of the [minum number of target levels](https://github.com/stfxecutables/df-analyze/blob/bbaa7c3d36b78a26faed2572feacb8c1931176d2/src/df_analyze/_constants.py#L112-L131), you definitely don't have enough data. 

What is the size of your dataset? I.e. what is the number of rows, and number of features (columns)? How many classes are there in your target, and how many samples are there per each target class?

**Comment by theahmadzai** [comment]
Thank you for checking out the issue, I'm looking into that our dataset has 42k records, following are the details
![1](https://github.com/user-attachments/assets/dfacec4b-1361-48a1-b416-6257e394b80d)
![2](https://github.com/user-attachments/assets/b6c8f3b4-af33-4bfc-ae56-7bc5f929dd9c)

Around 700 values are above value `1000` while the rest of distribution seems fine, found that out after creating issue, will try to fix it on our end.

**Comment by DM-Berger** [comment]
Alright, so more specifically, what is your _target_ variable, and are you doing classification? The above error should only really show up for classification problems where the target variable has undersampled levels (i.e. not enough classes for a particular target level for performance metrics or training to be expected to meaningfully generalize). 

A way to get stats on a classification target is to use `uniques, counts = np.unique(y, return_counts=True)` on that target variable / feature `y`. Most likely you will see in the `counts` variable that there are a number of values less than about 20-50.

**Comment by theahmadzai** [comment]
Oh shoot, it's a regression problem did not pay close attention to the command I was running, perhaps I should have looked into the parameters passed, thank you so much for your responses I think we can close the issue, We're able to run it successfully, @salalalikhan @moayadeldin

**Comment by DM-Berger** [comment]
No worries, lots of options, easy to overlook! Glad it is working for you.
